<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../DP.Vision/DP.Vision.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="DP.Vision.Winform" />
        <InternalsVisibleTo Include="DP.Vision.WPF" />
        <InternalsVisibleTo Include="DP.Vision.Tests" />
    </ItemGroup>
</Project>
