<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../DP.Vision/DP.Vision.csproj" />
        <ProjectReference Include="../DP.Vision.Acquisition.Runtime/DP.Vision.Acquisition.Runtime.csproj" />
    </ItemGroup>
</Project>
