<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/DP.Vision.Acquisition.Abstractions/DP.Vision.Acquisition.Abstractions.csproj" />
        <ProjectReference Include="../../src/DP.Vision.Acquisition.Runtime/DP.Vision.Acquisition.Runtime.csproj" />
        <ProjectReference Include="../../src/DP.Vision.Acquisition.Management/DP.Vision.Acquisition.Management.csproj" />
        <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    </ItemGroup>
</Project>
